# Name of the GitHub Actions workflow
name: Build, Test and Push Image CI

# Specifies the events that trigger the workflow
on:
# Trigger the workflow on a push event
  push:
    branches:
      - main

# Defines the jobs in the workflow
jobs:
  build:
    runs-on: ubuntu-latest

    # Steps to be executed in the job
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - # Step to set up Docker Buildx
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - # Step to build and test the Docker image
        name: Build and test
        uses: docker/build-push-action@v6
        with:
          target: build
          load: true
      - # Step to build and push the Docker image to Docker Hub
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          target: final
          tags: ${{ vars.DOCKER_USERNAME }}/${{ github.event.repository.name }}:latest
